name: hello_world
description: A new Flutter project.       

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.1.0
  get: ^4.6.5
  lottie: ^1.4.2
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.9
  flutter_riverpod: ^1.0.0
  provider: ^5.0.0
  firebase_core: ^1.1.0
  cloud_firestore: ^2.0.0
  firebase_auth: ^1.1.3
  

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/animations/
    - assets/images/
    - assets/
    
   
    
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
